@host = http://127.0.0.1:5000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJfaWQiOiJkZjIwNTEwOS1mNmYxLTExZWMtYjMyYy01NjZmZTE0MTAyNzQiLCJlbWFpbCI6InNlcmdpby53ZWxsaW5ndG9uQHRyYW5zZmVyby5jb20ifSwiZXhwaXJlcyI6bnVsbH0.O6sOt5LxM1_FpojLCS_yn5cxg5hbQYJRDivf7vtJaHU

POST {{host}}/owners HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "user_id":"79",
    "system_id":"3"
}
###

DELETE {{host}}/owners/4 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###

GET {{host}}/owners/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###

GET {{host}}/owners/4 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###

GET {{host}}/owners/systems/test@endtoend.com HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###
