from .ifunction_repository import IFunctionRepository
from .ipaper_repository import IPaperRepository
from .ifeature_repository import IFeatureRepository
from .isystem_repository import ISystemRepository
from .iuser_permission_repository import IUserPermissionRepository
from .iuser_repository import IUserRepository
from .isystem_permission_repository import ISystemPermissionRepository
from .iowner_repository import IOwnerRepository  